/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_DEMO_PB_H_INCLUDED
#define PB_DEMO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _sensor {
    float temperature;
    int32_t humidity;
} sensor;

typedef struct _device {
    sensor indoor_sensor;
    sensor outdoor_sensor;
    char payload[64];
} device;


/* Initializer values for message structs */
#define sensor_init_default                      {0, 0}
#define device_init_default                      {sensor_init_default, sensor_init_default, ""}
#define sensor_init_zero                         {0, 0}
#define device_init_zero                         {sensor_init_zero, sensor_init_zero, ""}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_temperature_tag                   1
#define sensor_humidity_tag                      2
#define device_indoor_sensor_tag                 1
#define device_outdoor_sensor_tag                2
#define device_payload_tag                       3

/* Struct field encoding specification for nanopb */
#define sensor_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature,       1) \
X(a, STATIC,   REQUIRED, INT32,    humidity,          2)
#define sensor_CALLBACK NULL
#define sensor_DEFAULT NULL

#define device_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  indoor_sensor,     1) \
X(a, STATIC,   REQUIRED, MESSAGE,  outdoor_sensor,    2) \
X(a, STATIC,   REQUIRED, STRING,   payload,           3)
#define device_CALLBACK NULL
#define device_DEFAULT NULL
#define device_indoor_sensor_MSGTYPE sensor
#define device_outdoor_sensor_MSGTYPE sensor

extern const pb_msgdesc_t sensor_msg;
extern const pb_msgdesc_t device_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_fields &sensor_msg
#define device_fields &device_msg

/* Maximum encoded size of messages (where known) */
#define sensor_size                              16
#define device_size                              101

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
