/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "demo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor, sensor, AUTO)


PB_BIND(device, device, AUTO)



